
# C:\Python34\parser\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '8F03EAEA5D882C795A9FED088615738A'
    
_lr_action_items = {'COMMA':([11,12,20,21,23,28,29,31,56,],[16,-31,16,-32,16,-36,-37,-35,66,]),'JOIN':([12,20,21,36,63,75,83,],[-31,33,-32,53,33,33,33,]),'NEQ':([24,25,28,29,31,32,],[-33,45,-36,-37,-35,-34,]),'DOT':([67,81,],[73,82,]),'ON':([50,],[61,]),'AND':([24,26,27,28,29,31,32,49,54,55,57,58,59,60,62,],[-33,-25,46,-36,-37,-35,-34,46,46,46,-26,-23,46,-24,46,]),'RPAREN':([24,26,28,29,31,32,49,57,58,59,60,],[-33,-25,-36,-37,-35,-34,60,-26,-23,-22,-24,]),'OR':([24,26,27,28,29,31,32,49,54,55,57,58,59,60,62,],[-33,-25,48,-36,-37,-35,-34,48,48,48,-26,-23,-22,-24,48,]),'EOL':([12,14,20,21,22,24,26,27,28,29,31,32,34,54,55,56,57,58,59,60,62,63,69,70,71,74,75,77,78,80,83,84,85,86,],[-31,18,35,-32,38,-33,-25,47,-36,-37,-35,-34,52,64,65,-14,-26,-23,-22,-24,68,69,-18,74,-15,-21,77,-16,80,-19,84,-17,86,-20,]),'STRING':([19,30,37,39,40,41,42,43,44,45,46,48,51,],[29,29,29,29,29,-30,-29,29,-27,-28,29,29,29,]),'LPAREN':([19,30,37,39,46,48,51,],[30,30,30,30,30,30,30,]),'WHERE':([12,14,20,21,22,28,29,31,34,56,69,71,74,77,80,84,86,],[-31,19,37,-32,39,-36,-37,-35,51,-14,-18,-15,-21,-16,-19,-17,-20,]),'INT':([19,30,37,39,40,41,42,43,44,45,46,48,51,],[31,31,31,31,31,-30,-29,31,-27,-28,31,31,31,]),'UPDATE':([0,],[5,]),'FROM':([1,9,10,11,12,21,],[8,-12,15,-13,-31,-32,]),'DELETE':([0,],[1,]),'ID':([4,5,8,15,16,17,19,30,33,37,39,41,42,43,44,45,46,48,51,53,61,66,72,73,79,82,],[12,13,14,12,21,12,24,24,50,24,24,-30,-29,24,-27,-28,24,24,24,63,67,12,75,76,81,83,]),'GT':([24,25,28,29,31,32,],[-33,42,-36,-37,-35,-34,]),'EQ':([12,21,23,24,25,28,29,31,32,67,76,],[-31,-32,40,-33,44,-36,-37,-35,-34,72,79,]),'SELECT':([0,],[4,]),'SET':([13,],[17,]),'DOUBLE':([19,30,37,39,40,41,42,43,44,45,46,48,51,],[28,28,28,28,28,-30,-29,28,-27,-28,28,28,28,]),'$end':([2,3,6,7,18,35,38,47,52,64,65,68,],[0,-2,-1,-3,-10,-6,-4,-11,-8,-7,-5,-9,]),'LT':([24,25,28,29,31,32,],[-33,41,-36,-37,-35,-34,]),'ALL':([4,],[9,]),'NATURAL':([12,20,21,63,75,83,],[-31,36,-32,36,36,36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[2,]),'select_statement':([0,],[3,]),'value':([19,30,37,39,43,46,48,51,],[25,25,25,25,57,25,25,25,]),'comp_op':([25,],[43,]),'set_clause_list':([17,66,],[22,71,]),'id_list':([4,15,17,66,],[11,20,23,23,]),'search_condition':([19,30,37,39,46,48,51,],[27,49,54,55,58,59,62,]),'comparison_predicate':([19,30,37,39,46,48,51,],[26,26,26,26,26,26,26,]),'join_clause':([20,63,75,83,],[34,70,78,85,]),'select_columns':([4,],[10,]),'update_statement':([0,],[6,]),'delete_statement':([0,],[7,]),'literal':([19,30,37,39,40,43,46,48,51,],[32,32,32,32,56,32,32,32,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> update_statement','statement',1,'p_statement','update_select_delete.py',96),
  ('statement -> select_statement','statement',1,'p_statement','update_select_delete.py',97),
  ('statement -> delete_statement','statement',1,'p_statement','update_select_delete.py',98),
  ('update_statement -> UPDATE ID SET set_clause_list EOL','update_statement',5,'p_update_statement','update_select_delete.py',103),
  ('update_statement -> UPDATE ID SET set_clause_list WHERE search_condition EOL','update_statement',7,'p_update_statement','update_select_delete.py',104),
  ('select_statement -> SELECT select_columns FROM id_list EOL','select_statement',5,'p_select_statement','update_select_delete.py',107),
  ('select_statement -> SELECT select_columns FROM id_list WHERE search_condition EOL','select_statement',7,'p_select_statement','update_select_delete.py',108),
  ('select_statement -> SELECT select_columns FROM id_list join_clause EOL','select_statement',6,'p_select_statement','update_select_delete.py',109),
  ('select_statement -> SELECT select_columns FROM id_list join_clause WHERE search_condition EOL','select_statement',8,'p_select_statement','update_select_delete.py',110),
  ('delete_statement -> DELETE FROM ID EOL','delete_statement',4,'p_delete_statement','update_select_delete.py',113),
  ('delete_statement -> DELETE FROM ID WHERE search_condition EOL','delete_statement',6,'p_delete_statement','update_select_delete.py',114),
  ('select_columns -> ALL','select_columns',1,'p_select_columns','update_select_delete.py',117),
  ('select_columns -> id_list','select_columns',1,'p_select_columns','update_select_delete.py',118),
  ('set_clause_list -> id_list EQ literal','set_clause_list',3,'p_set_clause_list','update_select_delete.py',121),
  ('set_clause_list -> id_list EQ literal COMMA set_clause_list','set_clause_list',5,'p_set_clause_list','update_select_delete.py',122),
  ('join_clause -> JOIN ID ON ID EQ ID EOL','join_clause',7,'p_join_clause','update_select_delete.py',125),
  ('join_clause -> JOIN ID ON ID DOT ID EQ ID DOT ID EOL','join_clause',11,'p_join_clause','update_select_delete.py',126),
  ('join_clause -> NATURAL JOIN ID EOL','join_clause',4,'p_join_clause','update_select_delete.py',127),
  ('join_clause -> JOIN ID ON ID EQ ID join_clause EOL','join_clause',8,'p_join_clause','update_select_delete.py',128),
  ('join_clause -> JOIN ID ON ID DOT ID EQ ID DOT ID join_clause EOL','join_clause',12,'p_join_clause','update_select_delete.py',129),
  ('join_clause -> NATURAL JOIN ID join_clause EOL','join_clause',5,'p_join_clause','update_select_delete.py',130),
  ('search_condition -> search_condition OR search_condition','search_condition',3,'p_search_condition','update_select_delete.py',133),
  ('search_condition -> search_condition AND search_condition','search_condition',3,'p_search_condition','update_select_delete.py',134),
  ('search_condition -> LPAREN search_condition RPAREN','search_condition',3,'p_search_condition','update_select_delete.py',135),
  ('search_condition -> comparison_predicate','search_condition',1,'p_search_condition','update_select_delete.py',136),
  ('comparison_predicate -> value comp_op value','comparison_predicate',3,'p_comparison_predicate','update_select_delete.py',139),
  ('comp_op -> EQ','comp_op',1,'p_comp_op','update_select_delete.py',142),
  ('comp_op -> NEQ','comp_op',1,'p_comp_op','update_select_delete.py',143),
  ('comp_op -> GT','comp_op',1,'p_comp_op','update_select_delete.py',144),
  ('comp_op -> LT','comp_op',1,'p_comp_op','update_select_delete.py',145),
  ('id_list -> ID','id_list',1,'p_id_list','update_select_delete.py',148),
  ('id_list -> id_list COMMA ID','id_list',3,'p_id_list','update_select_delete.py',149),
  ('value -> ID','value',1,'p_value','update_select_delete.py',157),
  ('value -> literal','value',1,'p_value','update_select_delete.py',158),
  ('literal -> INT','literal',1,'p_literal','update_select_delete.py',161),
  ('literal -> DOUBLE','literal',1,'p_literal','update_select_delete.py',162),
  ('literal -> STRING','literal',1,'p_literal','update_select_delete.py',163),
]
